### ISSUE TITLE
Why are you copyrighting and reserving the rights for this?

### ISSUE THREAD

**Issue by TheYoungSeth** [BobVarioa/kjsarsnouveau#3]
I really don't wanna sound mean here cause it's a genuine question. I wanted to use this addon for my expert modpack, but due to the licensing here being strict I can't. I wanted to ask if there's a reason for this. I can remove the mod from my modpack if you guys really have an issue with it.

**Comment by BobVarioa** [comment]
Oh I just forgot to put a real license, that's completely my fault. All my mods can always be used in any modpacks (though I would prefer if they were distributed through Curseforge) and are always licensed under MIT. I'll update the license now.
